import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Foundations of Physical AI',
      items: ['foundations/week-1-intro'],
    },
    {
      type: 'category',
      label: 'ROS 2',
      items: [{type: 'autogenerated', dirName: '02-ros2'}],
    },
    {
      type: 'category',
      label: 'Digital Twin Workflows',
      items: [{type: 'autogenerated', dirName: '03-digital-twin'}],
    },
    {
      type: 'category',
      label: 'NVIDIA Isaac',
      items: [{type: 'autogenerated', dirName: '04-isaac-sim'}],
    },
    {
      type: 'category',
      label: 'VLA Models & Humanoids',
      items: [{type: 'autogenerated', dirName: '05-vla-humanoids'}],
    },
    {
      type: 'category',
      label: 'Platform Setup',
      items: [{type: 'autogenerated', dirName: 'setup'}],
    },
  ],
};

export default sidebars;
